name: CI/CD

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build the app
      run: |
        npm run build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: build
